# Generated by Django 2.0.1 on 2018-02-26 21:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AddLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('add_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('answer', models.CharField(max_length=250)),
                ('add_at', models.DateTimeField(auto_now=True)),
                ('update_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuizDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detail', models.CharField(max_length=250)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Question')),
            ],
        ),
        migrations.CreateModel(
            name='QuizLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=250)),
                ('user_email', models.CharField(max_length=250, unique=True)),
                ('user_organization', models.CharField(max_length=250)),
                ('user_password', models.CharField(max_length=250)),
                ('is_related', models.BooleanField()),
                ('is_doctor', models.BooleanField()),
                ('is_admin', models.BooleanField(default=False)),
                ('add_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AddField(
            model_name='quizlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.User'),
        ),
        migrations.AddField(
            model_name='quizdetail',
            name='quizLog',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.QuizLog'),
        ),
        migrations.AddField(
            model_name='addlog',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.Question'),
        ),
        migrations.AddField(
            model_name='addlog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collection.User'),
        ),
    ]
