# Generated by Django 2.0.1 on 2018-02-26 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_doctor',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_related',
        ),
        migrations.RemoveField(
            model_name='user',
            name='user_organization',
        ),
    ]
